version: '3.4'
services:
  postgres-shop:
    image: postgres:12.1
    container_name: postgres-shop
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6444:5432
  migrations-shop:
    container_name: migrations-shop
    command: migrate
    depends_on:
      - postgres-shop
    build:
      context: ./migrations
      dockerfile: ./Dockerfile
